---
title: "Bowtie Aligner Consolidate Report"
output: html_document
params:
  inputPath: "NONE"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(dplyr)
library(stringr)
library(kableExtra)
```

---
# Import reports
---

```{r read_files, include = FALSE}

# dirs <- list.dirs(path=params$inputPath, full.names=TRUE, recursive=FALSE)
#
# for(a in 1:length(dirs)){
#  split_str <- dirs[a] %>%
#    str_split("/") %>%
#    .[[1]]
#  
#  sampleName <- split_str[length(split_str)]
#
#  temp_df <- read_tsv(paste(dirs[a],"/report/report.tsv",sep=""), comment = '##', col_names = c('Metric','Value'))

reportfilenames <- list.files(path=params$inputPath, full.names=TRUE, recursive=FALSE)

for(a in 1:length(reportfilenames)){
  split_str <- reportfilenames[a] %>%
    str_split("/") %>%
    .[[1]]
  
  split_str <- split_str[length(split_str)] %>%
    str_split("_") %>%
    .[[1]]
  
  sampleName <- split_str[1]

  temp_df <- read_tsv(reportfilenames[a], comment = '##', col_names = c('Metric','Value'))

# this part may not be necessary since temp_df will only have 2 columns
  if(length(temp_df) > 2){
    temp_stats_df <- temp_df[is.na(temp_df[5]),]
    temp_stats_df <- temp_stats_df[is.na(temp_stats_df[3]),]
    temp_stats_df <- temp_stats_df[c(1,2)]

    df <- temp_df[!is.na(temp_df[5]),]
    df <- df[(df$Metric != '#'),]
    df <- df[(df$Metric != 'rRNA'),]

    counts_df <- df[c(1,2)]
    names(counts_df)[2] <- "Value"
    counts_df$Metric <- paste(counts_df$Metric,"counts")

    rpkm_df <- df[c(1,3)]
    names(rpkm_df)[2] <- "Value"
    rpkm_df$Metric <- paste(rpkm_df$Metric,"rpkm")

    tpm_df <- df[c(1,4)]
    names(tpm_df)[2] <- "Value"
    tpm_df$Metric <- paste(tpm_df$Metric,"tpm")

    df <- temp_df[is.na(temp_df[5]),]
    df <- df[!is.na(df[3]),]
    df <- df[(df$Metric != '#'),]
    df <- df[(df$Metric != 'rRNA biotype'),]
    df <- df[c(1:3)]

    biotype_percent_df <- df[c(1,2)]
    names(biotype_percent_df)[2] <- "Value"
    biotype_percent_df$Metric <- paste(biotype_percent_df$Metric,"percent of total")
    biotype_count_df <- df[c(1,3)]
    names(biotype_count_df)[2] <- "Value"
    biotype_count_df$Metric <- paste(biotype_count_df$Metric,"counts")

    if(dim(counts_df)[1] > 0){
      temp_stats_df <- union(temp_stats_df,counts_df)
      temp_stats_df <- union(temp_stats_df,rpkm_df)
      temp_stats_df <- union(temp_stats_df,tpm_df)
      temp_stats_df <- union(temp_stats_df,biotype_percent_df)
      temp_stats_df <- union(temp_stats_df,biotype_count_df)
    }
  } else {
    temp_stats_df <- temp_df
  }

  if(a == 1){
    stats_df <- temp_stats_df %>%
      rename(!!sampleName := Value)
  }

  if(a > 1){
    stats_df <- stats_df %>%
      mutate(!!sampleName := temp_stats_df$Value[match(Metric,temp_stats_df$Metric)])
  }
}

names(stats_df)[1] <- ' '

```

```{r print_pipelineInfo, echo = FALSE}

knitr::kable(stats_df) %>%
  kable_styling(bootstrap_options = c("striped"), font_size = 12, full_width = T)

```

```{r write_to_file, include=FALSE}

write_tsv(stats_df,'consolidated_report.tsv')

```
